### ISSUE TITLE
about the sms config

### ISSUE THREAD

**Issue by Diluka** [cooper-lyt/keycloak-phone-provider#7]
when using docker, how to set

-  sms platform
-  sms key
-  sms sign
-  sms templete
-  or something else about sms

**Comment by Diluka** [comment]
https://github.com/cooper-lyt/keycloak-phone-provider/blob/e1cf55dd8e18282c1d6a1583896eace1c2a414fc/jboss-cli/module-add.cli#L68-L74

is this the config? but why some have template and others not?

**Comment by Diluka** [comment]
I find out a solution, but not sure if it is the right one.

### for aliyun sms

1. copy this file and change it as comment says
https://github.com/cooper-lyt/keycloak-phone-provider/blob/e1cf55dd8e18282c1d6a1583896eace1c2a414fc/keycloak-sms-provider-aliyun/configure.cli#L1-L23

2. create a Dockerfile

```Dockerfile
# keycloak/Dockerfile
FROM coopersoft/keycloak-phone:11.0.3

COPY configure-sms.cli cli/
RUN $JBOSS_HOME/bin/jboss-cli.sh --file=cli/configure-sms.cli
RUN rm -rf $JBOSS_HOME/standalone/configuration/standalone_xml_history/current
 ```

3. and use the image create local

```yml
version: "3.4"

x-aliyun-sms: &aliyun-sms
  SMS_PROVIDER_SERVER: aliyun
  ALIYUN_ACCESS_KEY_ID: ----
  ALIYUN_ACCESS_SECRET: ----
  ALIYUN_VERIFY_TEMPLATE: ----
  ALIYUN_OTP_TEMPLATE: ----
  ALIYUN_RESET_TEMPLATE: ----
  ALIYUN_REGISTRATION_TEMPLATE: ----

services: 
  auth:
    container_name: keycloak
    build: ./keycloak
    image: keycloak-phone
    logging: *logging
    environment: 
      JDBC_PARAMS: useSSL=false
      DB_VENDOR: mysql
      DB_ADDR: db
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 123456
      << : *aliyun-sms
    depends_on: 
    - db
```

**the `sms sign` is using the display name of realm. why not configure it like above?** @cooper-lyt
